spring:
  application:
    name: clsoftlab

  devtools:
    restart:
      enabled: true

# 용량 제한용
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
        
#  db 생성 전이라면 아래 코드 주석을 해제해서 써주세요.
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# db 생선 전이라면 아래 코드를 주석처리 해주세요. 61.74.135.228:3306 root  clsoftlab2024!@#
# db를 생성하셨다면 사용하신 db의 username과 비밀번호를 설정해주세요.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://61.74.135.228:3306/clsoftlabnew
    username: root
    password: clsoftlab2024!@#

# 테스트용 임시 key
encrypt:
  hmac:
    key: "ClSoftLabTestSecretHMACKey!@#$12"


# 테스트용 파일 업로드 경로
file:
  upload:
    dir: "${user.dir}/uploads/"